### ISSUE TITLE
V3.0 Start Services Failure

### ISSUE THREAD

**Issue by hawshemi** [GFW-knocker/MahsaNG#17]
After the v3.0 update. nothing works. I tested all IPSs and all configurations possible but the service won't start and it returns: `Start Services Failure`. Nothing will connect.

**Comment by mygit28** [comment]
Hello
I have the same problem and I installed the previous version.

**Comment by hawshemi** [comment]
> Hello I have the same problem and I installed the previous version.

Yes, the previous version is "somewhat" working. but the new version `v3.0` is not working at all.

**Comment by hawshemi** [comment]
The app is working after the update https://github.com/GFW-knocker/MahsaNG/releases/latest .
