### ISSUE TITLE
رمزنگاری کانفیگ‌ها

### ISSUE THREAD

**Issue by yaghobmn** [GFW-knocker/MahsaNG#6]
سلام و تشکر برای تلاش‌هاتون
چند وقت پیش امین انواری برنامه v2rayng رو ویرایش کرده بودند و به اسم برنامه sansorchi تو کانال تلگرامشون منتشر کرده بودن. همه چیز خوب پیش می‌رفت تا اینکه عده‌ای اومدن کانفیگ‌های برنامه رو استخراج کردن و تو تلگرام پخش شد که باعث فیلترشدن سرورهاش شد. پیشنهاد میدم از همین ابتدا این موضوع رو هم در نظر بگیرید تا اتفاقی مشابه رخ نده.
لینک اپ سانسورچی در کانال تلگرامشون
https://t.me/ml9Qk0OUpkNzFl/512
توییتر امین انواری
https://twitter.com/AminAnvary

**Comment by GFW-knocker** [comment]
ممنون. ما همین الان رمزنگاری AES داریم و در نسخه های بعدی uuid رو هم در runtime میایم decrypt میکنیم که فقط خود خدا بتونه استخراج کنه

**Comment by GFW-knocker** [comment]
ممکنه یه سری آفتابه دزد موقتا چند تا کانفیگ سرقت کنند اما تا زمانی که سرور دست ما هست جای نگرانی وجود نداره و در فرصت مقتضی از سمت سرور جلوی تمام این ها گرفته میشه. اپ مهسا چیزی نیست که با این کارا بخواد زمین بخوره
